name: tripTracker
description: App to record your trips

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.15.6
  sqflite: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
