name: test_proj
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
